### ISSUE TITLE
Exception/Closed MySQL connections on every request

### ISSUE THREAD

**Issue by hexuallyactive** [Flipkart/phantom-mysql-proxy#1]
Hi, whenever I run a query against mysql via the proxy, the connection gets closed and the proxy server logs:

01:31:39.123 [New I/O server worker #1-1] WARN  c.f.p.r.i.s.n.h.m.MysqlChannelHandler - Exception [id: 0x0af69121, /127.0.0.1:59273 => /127.0.0.1:8080] EXCEPTION: java.net.SocketException: Socket closed thrown on Channel [id: 0x0af69121, /127.0.0.1:59273 => /127.0.0.1:8080]. Disconnect initiated
Aug 27, 2014 1:31:39 AM org.jboss.netty.channel.SimpleChannelHandler
WARNING: EXCEPTION, please implement com.flipkart.phantom.runtime.impl.server.netty.handler.mysql.MysqlChannelHandler.exceptionCaught() for proper handling.
java.net.SocketException: Socket closed
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:121)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:147)
    at com.github.mpjct.jmpjct.mysql.proto.Packet.write(Unknown Source)
    at com.flipkart.phantom.runtime.impl.server.netty.handler.mysql.MysqlChannelHandler.executeQueries(MysqlChannelHandler.java:333)
    at com.flipkart.phantom.runtime.impl.server.netty.handler.mysql.MysqlChannelHandler.handleQueries(MysqlChannelHandler.java:316)
    at com.flipkart.phantom.runtime.impl.server.netty.handler.mysql.MysqlChannelHandler.messageReceived(MysqlChannelHandler.java:180)
    at com.flipkart.phantom.runtime.impl.server.netty.handler.mysql.MysqlChannelHandler.handleUpstream(MysqlChannelHandler.java:170)
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
    at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:327)
    at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:305)
    at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:207)
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:343)
    at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:274)
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:194)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)

**Comment by regunathb** [comment]
Kurt,

 Sharing these details will help us debug the issue:
1. Version of proxy you are using (or) is it built from github master.
2. Do you have a sample test case/class alongwith required table schema
   that we can use to reproduce the problem?
3. Need to see file contents of : spring-proxy-listener-config.xml
   and spring-proxy-handler-config.xml from your proxy configuration.

Regards
Regu

**Comment by hexuallyactive** [comment]
Hi Regu,

I am using github master.
MySQL version is 5.5.37.
I am using the default spring-proxy-listener-config.xml and spring-proxy-handler-config.xml
I don't have a test case readily available, but simply trying to use MySQL Workbench to connect to the proxy yields an exception.  I'll try to look into it further, but any info you might have certainly would help.

Thanks!
Kurt

**Comment by kormoc** [comment]
What version of mysql workbench? Which OS?

**Comment by hexuallyactive** [comment]
Hi Rob!

mysql workbench 6.1 on OS X.  I get a one exception using workbench, and a different exception when using the mysql cli from localhost (on the server, which is Ubuntu 12.04).  Let me know if there is anything else I can supply that might help.  

Kurt

**Comment by kormoc** [comment]
What version of MySQL and which fork (MySQL/MariaDB/etc)?

**Comment by hexuallyactive** [comment]
I'm using MySQL 5.5.37.  On a side note - I have also tried using jmpjct (master) as well as a proxy, and cannot seem to make it work either (although it did some time back).  I'll investigate older server versions, etc. and see if I can find a working version - maybe that will help us.

**Comment by samaitra** [comment]
Hi Kurt,

I am able to reproduce this issue when I am using mysql password. I have not faced this issue earlier but able to reproduce it in mysql version 5.6.19.

Can you try replacing your jdbc url to something like below.  
jdbc:mysql://localhost:8080/<YOUR_TABLE_HERE>?characterEncoding=utf8&user=root&password=

I tried with above jdbc url and the issue went away. I will investigate further and fix the issue.

Regards
Saikat

**Comment by samaitra** [comment]
Hello Kurt,

I was testing this issue using  unit tests which uses jdbc url and replied in that context above. I am able to reproduce the issue using Mysql workbench 6.1 when using valid user with password credentials.

The issue do not surface with user root and blank password. 

I am investigating it further.

Saikat

**Comment by samaitra** [comment]
Fixed.:)
